// --- START OF FILE notes.rs---

use serde::{Deserialize, Serialize};
// Zeroize prevents memory forensics by explicitly overwriting sensitive variables
// in RAM with zeroes (`0x00`) the exact moment they drop out of scope.
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Represents a single encrypted secure note (e.g., a journal entry or a list of seed phrases).
///
/// SECURITY IMPLEMENTATION:
/// When a user opens their vault, these structs are loaded into active RAM so the React
/// frontend can display them. By deriving `ZeroizeOnDrop`, the Rust compiler automatically
/// generates a `Drop` trait implementation that overwrites `title` and `content` with
/// zeros as soon as the `NoteEntry` is removed from memory (e.g., when the app exits,
/// the vault locks, or the user navigates away and the object is garbage-collected).
#[derive(Serialize, Deserialize, Debug, Clone, Zeroize, ZeroizeOnDrop)]
pub struct NoteEntry {
    pub id: String, // Unique UUID used by the React frontend for key tracking and updates
    pub title: String, // The headline of the note
    pub content: String, // The main body of the note (often contains highly sensitive info)
    pub created_at: i64, // Unix timestamp (seconds) of initial creation
    pub updated_at: i64, // Unix timestamp (seconds) of the last edit

    // Allows users to pin important notes (like an Emergency contact list) to the top of the UI
    #[serde(default)]
    pub is_pinned: bool,
}

/// The root container for all Secure Notes.
/// This entire struct is serialized into JSON and encrypted as a single payload into `notes.qre`.
#[derive(Serialize, Deserialize, Debug, Default, Zeroize, ZeroizeOnDrop)]
pub struct NotesVault {
    // Schema versioning allows for safe, backwards-compatible updates.
    // If we add new fields in V2, V1 vaults can still be loaded and migrated safely.
    #[serde(default = "NotesVault::default_schema_version")]
    pub schema_version: u32,
    pub entries: Vec<NoteEntry>,
}

impl NotesVault {
    // Defines the current data structure version expected by the backend
    pub const CURRENT_SCHEMA_VERSION: u32 = 1;

    // Fallback for older JSON files that might lack the version field entirely
    fn default_schema_version() -> u32 {
        1
    }

    /// Initializes a brand new, empty notes vault.
    pub fn new() -> Self {
        Self {
            schema_version: Self::CURRENT_SCHEMA_VERSION,
            entries: Vec::new(),
        }
    }

    /// Validates the internal integrity of the vault to prevent data corruption.
    /// This function is called *before* the backend saves the JSON to disk.
    pub fn validate(&self) -> Result<(), String> {
        // Prevent an older version of the app from overwriting and corrupting
        // a vault created by a newer version of the app.
        if self.schema_version > Self::CURRENT_SCHEMA_VERSION {
            return Err(format!(
                "Vault version {} is too new. Update app.",
                self.schema_version
            ));
        }

        let mut seen_ids = std::collections::HashSet::new();

        for note in &self.entries {
            // Ensure no empty/broken IDs were generated by a frontend bug
            if note.id.is_empty() {
                return Err("Note has empty ID".into());
            }
            // Ensure all IDs are strictly unique. Duplicate IDs would cause
            // React rendering bugs and accidental data overwrites on the frontend.
            if !seen_ids.insert(&note.id) {
                return Err(format!("Duplicate ID: {}", note.id));
            }
        }

        Ok(()) // Validation passed successfully
    }
}

// --- END OF FILE notes.rs ---
