// --- START OF FILE secure_rng.rs ---

// ==========================================
// --- MODULE CONFIGURATION ---
// ==========================================
// This attribute suppresses compiler warnings if this module or its functions
// aren't currently invoked elsewhere in the codebase. It allows this utility
// to remain in the project for future use (like deterministic key derivation).
#![allow(dead_code)]

use rand::{RngCore, SeedableRng};
// ChaCha20 is a stream cipher developed by Daniel J. Bernstein. It is incredibly fast,
// immune to timing side-channel attacks (unlike AES on CPUs without AES-NI), and is
// the gold standard for CSPRNGs (used in TLS 1.3, WireGuard, and Linux /dev/urandom).
use rand_chacha::ChaCha20Rng;

// ==========================================
// --- DATA STRUCTURES ---
// ==========================================

/// A wrapper around a Cryptographically Secure Pseudo-Random Number Generator (CSPRNG).
///
/// While the standard `OsRng` asks the Operating System for random bytes every time,
/// `SecureEngine` uses a specific 32-byte seed to generate a massive, secure,
/// and *reproducible* stream of bytes.
///
/// This implementation uses the ChaCha20 algorithm, which is:
/// 1. Fast (suitable for generating gigabytes of random noise for secure file shredding).
/// 2. Secure (resistant to all known prediction and cryptographic attacks).
/// 3. Deterministic (if seeded with the exact same 32 bytes, it produces the exact same stream).
pub struct SecureEngine {
    rng: ChaCha20Rng,
}

impl SecureEngine {
    /// Initializes the cryptographic engine with a specific 32-byte (256-bit) seed.
    ///
    /// SECURITY: This seed determines the entire output of the generator. It should
    /// come from a highly secure source, such as the `entropy` module (mixing user mouse
    /// movements, system time, and OS randomness), or a derived master password.
    pub fn new(seed: [u8; 32]) -> Self {
        Self {
            rng: ChaCha20Rng::from_seed(seed),
        }
    }

    /// Fills an arbitrary-sized mutable buffer with cryptographically secure random bytes.
    ///
    /// This is the core primitive used to generate random noise (for the file shredder),
    /// salts (for password hashing), or nonces/IVs (for AES-GCM encryption).
    pub fn fill_bytes(&mut self, dest: &mut [u8]) {
        self.rng.fill_bytes(dest);
    }

    /// Convenience helper function to generate a fresh, random 32-byte key.
    ///
    /// 32 bytes (256 bits) is the exact length required for an AES-256 or ChaCha20 key,
    /// providing a post-quantum secure cryptographic margin.
    pub fn gen_aes_key(&mut self) -> [u8; 32] {
        let mut key = [0u8; 32];
        // Calls the internal helper method to populate the fixed-size array.
        self.fill_bytes(&mut key);
        key
    }
}

// ==========================================
// --- MEMORY SAFETY ---
// ==========================================

// Ensures the RNG state is handled correctly when the object goes out of scope.
impl Drop for SecureEngine {
    fn drop(&mut self) {
        // The `ChaCha20Rng` implementation generally handles its own internal cleanup.
        // However, in strict cryptographic environments, the internal state (the seed
        // and internal matrix) should be explicitly zeroized here to prevent attackers
        // from dumping the RAM, extracting the state, and predicting past or future
        // random numbers generated by this specific instance.
        // If this struct held raw sensitive seeds directly in its own fields,
        // explicit memory zeroing via the `zeroize` crate would happen here.
    }
}

// ==========================================
// --- TESTS ---
// ==========================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Verifies that the RNG is perfectly deterministic.
    /// In cryptography, it is critical that the same seed produces the exact same output stream.
    /// This property allows for reproducible encryption keys if a user recovers their vault
    /// using a known recovery seed phrase.
    #[test]
    fn test_prng_determinism() {
        let seed = [42u8; 32]; // A dummy fixed seed
        let mut eng1 = SecureEngine::new(seed);
        let mut eng2 = SecureEngine::new(seed);

        let mut out1 = [0u8; 16];
        let mut out2 = [0u8; 16];

        eng1.fill_bytes(&mut out1);
        eng2.fill_bytes(&mut out2);

        // Both engines must produce the exact same 16 random bytes
        assert_eq!(out1, out2);
    }

    /// Verifies that different seeds produce completely different outputs.
    /// This ensures the "Avalanche Effect"—even a tiny change in the starting entropy
    /// (e.g., changing a 1 to a 2) results in a completely unpredictable, unrelated byte stream.
    #[test]
    fn test_prng_uniqueness() {
        let seed1 = [1u8; 32];
        let seed2 = [2u8; 32]; // Only 1 byte difference from seed1

        let mut eng1 = SecureEngine::new(seed1);
        let mut eng2 = SecureEngine::new(seed2);

        let mut out1 = [0u8; 32];
        let mut out2 = [0u8; 32];

        eng1.fill_bytes(&mut out1);
        eng2.fill_bytes(&mut out2);

        // The outputs must not match
        assert_ne!(out1, out2);
    }
}

// --- END OF FILE secure_rng.rs ---
